version: '3'

services:
  selenium:
    container_name: selenium_automation
    ports:
      - 4444:4444
      - 5900:5900
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./test:/test
